### ISSUE TITLE
改变scheduler部署的参数，scheduler无法启动

### ISSUE THREAD

**Issue by tommenx** [Rhealb/extender-scheduler#1]
我的k8s版本是1.13.1，使用kubeadm部署的k8s集群，我根据你的项目的描述了，改变了scheduler的部署的yaml文件之后，scheduler就无法启动，能帮忙看看嘛？
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --policy-config=/etc/kubernetes/scheduler-config.json
    - --leader-elect=true
    image: registry.aliyuncs.com/google_containers/kube-scheduler:v1.13.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /etc/kubernetes/scheduler-config.json
      name: policyconfig
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /etc/kubernetes/scheduler-config.json
      type: FileOrCreate
    name: policyconfig
status: {}
```
